language: python

python:
  - "2.7"

before_install:
  - "sudo apt-get purge openjdk*"
  - "sudo apt-get purge oracle-java7-*"

addons:
  apt:
    packages:
    - oracle-java8-installer
    - oracle-java8-set-default

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - AWS_ACCESS_KEY_ID=foobar
    - AWS_SECRET_ACCESS_KEY=foobar
    - AWS_DEFAULT_REGION=us-east-1

install:
  - travis_wait 20 make install

script:
  - make test

after_success:  
  - make coveralls

notifications:
  email: false
